### ISSUE TITLE
Reverse the Dataset module

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/election-nepal#27]
Let's reverse the datasets module, the newly added datasets need to be in top, currently its opposite.

**Comment by sagargg** [comment]
fixed

**Comment by nikeshbalami** [comment]
![screen shot 2017-04-20 at 6 59 40 am](https://cloud.githubusercontent.com/assets/3656268/25209133/b2417ea0-2598-11e7-8155-db99a02a9f9c.png)
Still the same, not solved!!
